import {
  activeSaveIntentKeys,
  analysisSchemaForCollections,
  STARTER_COLLECTIONS,
} from "./config.ts";
import {
  bestEvidence,
  compactUrlEvidence,
  evidenceQuality,
  evidenceSources,
  fetchExtractusOembedEvidence,
  metaOembedEndpoint,
  normalizedUrlEvidence,
  oembedEndpoint,
  oembedMetadata,
  parseHtmlEvidence,
  platformForUrl,
  productEvidenceStatus,
  tier1CanonicalCandidates,
  weaknessReasons,
} from "./url-evidence.ts";
import {
  buildPrompt,
  buildOpenAiUserContent,
  captureGateMetadata,
  captureGateNeedsReviewAnalysis,
  captureGatePrompt,
  contentEvidenceProfile,
  normalizedReviewAnalysis,
  resolveReviewTargets,
  reviewTargetsForAnalysis,
  normalizeVisitTargetFields,
  shouldAnalyzeAfterCaptureGate,
  shouldAttachUrlEvidence,
  shouldRunCaptureGate,
  shouldRunPreflight,
  shouldRejectContextlessLinkCapture,
  shouldUseLinkOnlyUrlEvidenceFallback,
} from "./analysis.ts";
import {
  shouldSeedStarterCollections,
  starterCollectionRows,
} from "./collections.ts";
import {
  confirmedReminderFromInput,
  saveConfirmedReminderSuggestion,
} from "./collections/review-decisions.ts";

export const __urlEvidenceTest = {
  activeSaveIntentKeys,
  analysisSchemaForCollections,
  bestEvidence,
  buildOpenAiUserContent,
  buildPrompt,
  captureGateMetadata,
  captureGateNeedsReviewAnalysis,
  confirmedReminderFromInput,
  contentEvidenceProfile,
  captureGatePrompt,
  compactUrlEvidence,
  evidenceQuality,
  evidenceSources,
  fetchExtractusOembedEvidence,
  metaOembedEndpoint,
  normalizeVisitTargetFields,
  normalizedReviewAnalysis,
  normalizedUrlEvidence,
  oembedEndpoint,
  oembedMetadata,
  parseHtmlEvidence,
  platformForUrl,
  productEvidenceStatus,
  resolveReviewTargets,
  reviewTargetsForAnalysis,
  shouldAttachUrlEvidence,
  shouldRunCaptureGate,
  shouldRunPreflight,
  shouldRejectContextlessLinkCapture,
  shouldAnalyzeAfterCaptureGate,
  shouldUseLinkOnlyUrlEvidenceFallback,
  shouldSeedStarterCollections,
  saveConfirmedReminderSuggestion,
  starterCollectionRows,
  starterCollections: STARTER_COLLECTIONS,
  tier1CanonicalCandidates,
  weaknessReasons,
};
