import {
  activeSaveIntentKeys,
  analysisSchemaForCollections,
  STARTER_COLLECTIONS,
} from "./config.ts";
import {
  bestEvidence,
  compactUrlEvidence,
  emptyUrlEvidence,
  evidenceQuality,
  evidenceSources,
  exaContentsRequestBody,
  exaTargetUrlsForEnrichment,
  fetchExtractusOembedEvidence,
  fetchExaContentsEvidence,
  isExaContentsConfigured,
  metaOembedEndpoint,
  normalizeExaContentsEvidence,
  normalizedUrlEvidence,
  oembedEndpoint,
  oembedMetadata,
  parseHtmlEvidence,
  platformForUrl,
  productEvidenceStatus,
  shouldAttemptExaEnrichment,
  shouldUseCachedEvidence,
  tier1CanonicalCandidates,
  weaknessReasons,
} from "./url-evidence.ts";
import {
  buildPrompt,
  buildOpenAiUserContent,
  captureGateMetadata,
  captureGateNeedsReviewAnalysis,
  captureGatePrompt,
  captureRoleInstruction,
  captureRoleTraceFromCollections,
  contentEvidenceProfile,
  isVisualDownloadFailure,
  normalizedLocationContext,
  normalizedReviewAnalysis,
  resolveReviewTargets,
  reviewTargetsForAnalysis,
  normalizeVisitTargetFields,
  shouldAnalyzeAfterCaptureGate,
  shouldAttachUrlEvidence,
  shouldRunCaptureGate,
  shouldRunPreflight,
  shouldRejectContextlessLinkCapture,
  shouldUseLinkOnlyUrlEvidenceFallback,
  validateReminderIdeas,
} from "./analysis.ts";
import {
  COLLECTION_PROMPT_CANDIDATE_COUNT,
  COLLECTION_RETRIEVAL_MATCH_COUNT,
  promptCollectionsForAnalysis,
  shouldSeedStarterCollections,
  starterCollectionRows,
} from "./collections.ts";
import {
  confirmedReminderFromInput,
  saveConfirmedReminderSuggestion,
} from "./collections/review-decisions.ts";

export const __urlEvidenceTest = {
  activeSaveIntentKeys,
  analysisSchemaForCollections,
  bestEvidence,
  buildOpenAiUserContent,
  buildPrompt,
  captureGateMetadata,
  captureGateNeedsReviewAnalysis,
  COLLECTION_RETRIEVAL_MATCH_COUNT,
  confirmedReminderFromInput,
  contentEvidenceProfile,
  captureGatePrompt,
  captureRoleInstruction,
  captureRoleTraceFromCollections,
  compactUrlEvidence,
  COLLECTION_PROMPT_CANDIDATE_COUNT,
  emptyUrlEvidence,
  evidenceQuality,
  evidenceSources,
  exaContentsRequestBody,
  exaTargetUrlsForEnrichment,
  fetchExtractusOembedEvidence,
  fetchExaContentsEvidence,
  isExaContentsConfigured,
  isVisualDownloadFailure,
  metaOembedEndpoint,
  normalizeExaContentsEvidence,
  normalizedLocationContext,
  normalizeVisitTargetFields,
  normalizedReviewAnalysis,
  normalizedUrlEvidence,
  oembedEndpoint,
  oembedMetadata,
  parseHtmlEvidence,
  platformForUrl,
  promptCollectionsForAnalysis,
  productEvidenceStatus,
  resolveReviewTargets,
  reviewTargetsForAnalysis,
  shouldAttemptExaEnrichment,
  shouldAttachUrlEvidence,
  shouldUseCachedEvidence,
  shouldRunCaptureGate,
  shouldRunPreflight,
  shouldRejectContextlessLinkCapture,
  shouldAnalyzeAfterCaptureGate,
  shouldUseLinkOnlyUrlEvidenceFallback,
  shouldSeedStarterCollections,
  saveConfirmedReminderSuggestion,
  starterCollectionRows,
  starterCollections: STARTER_COLLECTIONS,
  tier1CanonicalCandidates,
  validateReminderIdeas,
  weaknessReasons,
};
